services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb_todo
    ports:
      - ${MARIA_BINDING_PORT}:${MARIA_PORT}
    volumes:
      - ${MARIA_DATA_PATH}:/var/lib/mariadb:rw
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIA_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIA_DATABASE}

  redis:
    image : redis:latest
    container_name: redis_todo
    ports:
      - ${REDIS_BINDING_PORT}:${REDIS_PORT}
    volumes:
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_DEFAULT_CONFIG_FILE}:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
